<a href="https://colab.research.google.com/github/Rakesh451-ai/Machine_Learning/blob/main/Random_Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

file_path = "diabetes_data.csv"

# Load the latest version
df = kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "tusharpotdar/diabetes-data",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:")
print(df.head())

Using Colab cache for faster access to the 'diabetes-data' dataset.
First 5 records:
   Unnamed: 0  Fasting_Blood_Glucose  Postprandial_Blood_Glucose     HbA1c  \
0           0             118.690215                  111.472598  5.570234
1           1             193.592860                  172.123161  5.481873
2           2             165.159212                  228.400792  9.437527
3           3             147.825603                  204.478231  5.497277
4           4              90.282423                  217.115395  5.631698

   Random_Blood_Glucose        BMI  Waist_Circumference  Triglyceride_Levels  \
0            224.721689  29.299897            37.872710           212.064239
1            253.236721  35.135808            39.468713            93.096591
2            127.607617  34.004023            47.090948           268.098641
3            213.721043  18.847498            36.800088           203.279060
4            201.501576  18.731237            47.392994            89.300971

   Blood_Pressure_Systolic  Blood_Pressure_Diastolic  ...  \
0                93.491951                100.418755  ...
1               106.809528                 98.109810  ...
2               164.812122                 56.702794  ...
3               159.009152                114.580068  ...
4               121.557842                 89.793054  ...

   Gestational_Diabetes  PCOS  Hypertension  Physical_Activity  Smoking  \
0                   Yes    No           Yes                Yes       No
1                   Yes    No            No                 No      Yes
2                    No    No            No                Yes      Yes
3                   Yes   Yes           Yes                 No       No
4                   Yes   Yes            No                Yes       No

   Alcohol_Consumption  Obesity  Diet  Sleep_Apnea  Diabetes_Status
0                  Yes       No    No           No         Positive
1                   No       No   Yes           No         Negative
2                   No      Yes    No           No         Positive
3                  Yes       No    No          Yes         Positive
4                  Yes       No   Yes          Yes         Positive

[5 rows x 36 columns]

In [ ]:
import os
import kagglehub

# Retrieve the actual path of the downloaded dataset
path = kagglehub.dataset_download("tusharpotdar/diabetes-data")

# Correctly evaluate the directory listing inside the f-string
print(f"contents of {path}:\n{os.listdir(path)}")

Using Colab cache for faster access to the 'diabetes-data' dataset.
contents of /kaggle/input/diabetes-data:
['diabetes_data.csv']

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
# ensamble --> bagging

In [ ]:
# classification report confusion matrices ka updated version

In [ ]:
df = pd.read_csv(os.path.join(path,"diabetes_data.csv"))

In [ ]:
df.head()

,Unnamed: 0,Fasting_Blood_Glucose,Postprandial_Blood_Glucose,HbA1c,Random_Blood_Glucose,BMI,Waist_Circumference,Triglyceride_Levels,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,...,Gestational_Diabetes,PCOS,Hypertension,Physical_Activity,Smoking,Alcohol_Consumption,Obesity,Diet,Sleep_Apnea,Diabetes_Status
0,0,118.690215,111.472598,5.570234,224.721689,29.299897,37.872710,212.064239,93.491951,100.418755,...,Yes,No,Yes,Yes,No,Yes,No,No,No,Positive
1,1,193.592860,172.123161,5.481873,253.236721,35.135808,39.468713,93.096591,106.809528,98.109810,...,Yes,No,No,No,Yes,No,No,Yes,No,Negative
2,2,165.159212,228.400792,9.437527,127.607617,34.004023,47.090948,268.098641,164.812122,56.702794,...,No,No,No,Yes,Yes,No,Yes,No,No,Positive
3,3,147.825603,204.478231,5.497277,213.721043,18.847498,36.800088,203.279060,159.009152,114.580068,...,Yes,Yes,Yes,No,No,Yes,No,No,Yes,Positive
4,4,90.282423,217.115395,5.631698,201.501576,18.731237,47.392994,89.300971,121.557842,89.793054,...,Yes,Yes,No,Yes,No,Yes,No,Yes,Yes,Positive

In [ ]:
df.shape # give dimension of dataset

(3000, 36)

In [ ]:
df.info()  # for know data tupe of colm's

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  3000 non-null   int64
 1   Fasting_Blood_Glucose       3000 non-null   float64
 2   Postprandial_Blood_Glucose  3000 non-null   float64
 3   HbA1c                       3000 non-null   float64
 4   Random_Blood_Glucose        3000 non-null   float64
 5   BMI                         3000 non-null   float64
 6   Waist_Circumference         3000 non-null   float64
 7   Triglyceride_Levels         3000 non-null   float64
 8   Blood_Pressure_Systolic     3000 non-null   float64
 9   Blood_Pressure_Diastolic    3000 non-null   float64
 10  LDL_Cholesterol             3000 non-null   float64
 11  HDL_Cholesterol             3000 non-null   float64
 12  CRP_Levels                  3000 non-null   float64
 13  Insulin_Levels              3000 non-null   float64
 14  HOMA_IR                     3000 non-null   float64
 15  OGTT                        3000 non-null   float64
 16  Creatinine_Levels           3000 non-null   float64
 17  eGFR                        3000 non-null   float64
 18  Microalbuminuria            3000 non-null   float64
 19  Uric_Acid_Levels            3000 non-null   float64
 20  Fructosamine_Levels         3000 non-null   float64
 21  ALT                         3000 non-null   float64
 22  AST                         3000 non-null   float64
 23  C_Peptide                   3000 non-null   float64
 24  Proinsulin_Levels           3000 non-null   float64
 25  Family_History_of_Diabetes  3000 non-null   object
 26  Gestational_Diabetes        3000 non-null   object
 27  PCOS                        3000 non-null   object
 28  Hypertension                3000 non-null   object
 29  Physical_Activity           3000 non-null   object
 30  Smoking                     3000 non-null   object
 31  Alcohol_Consumption         3000 non-null   object
 32  Obesity                     3000 non-null   object
 33  Diet                        3000 non-null   object
 34  Sleep_Apnea                 3000 non-null   object
 35  Diabetes_Status             3000 non-null   object
dtypes: float64(24), int64(1), object(11)
memory usage: 843.9+ KB

In [ ]:
# pick some columns --> Features selection
columns_to_pick = [
    "Insulin_Levels",
    "OGTT",
    "Creatinine_Levels",
    "Random_Blood_Glucose",
    "LDL_Cholesterol",
    "Uric_Acid_Levels"
]

In [ ]:
X = df[columns_to_pick]
Y = df["Diabetes_Status"]

In [ ]:
X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [ ]:
# 100 -- random trees

model = RandomForestClassifier(
    n_estimators=300,
    max_depth=5,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=22,
    n_jobs = -1
    )

In [ ]:
# labelencoder --> to change string to numerical data type
# positive -> 0
# negative -> 1
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
Y_train_encoded = le.fit_transform(Y_train)
# fit --> train model on trained data -> to remember data to model
Y_test_encoded = le.transform(Y_test)
# not write fit -> we not want to remember test data to model

model.fit(X_train,Y_train_encoded)

RandomForestClassifier(max_depth=5, min_samples_leaf=2, min_samples_split=5,
                       n_estimators=300, n_jobs=-1, random_state=22)

In [ ]:
Y_pred = model.predict(X_test)
accuracy = accuracy_score(Y_test_encoded,Y_pred)
print("Accuracy:",accuracy)

Accuracy: 0.8783333333333333

In [ ]:
print(classification_report(Y_test_encoded,Y_pred))

              precision    recall  f1-score   support

           0       0.98      0.75      0.85       271
           1       0.82      0.99      0.90       329

    accuracy                           0.88       600
   macro avg       0.90      0.87      0.87       600
weighted avg       0.90      0.88      0.88       600

In [ ]:

model.fit(X_train, Y_train_encoded) # (training_data , Output_data)

RandomForestClassifier(max_depth=5, min_samples_leaf=2, min_samples_split=5,
                       n_estimators=300, n_jobs=-1, random_state=22)

In [ ]:
# to know about which features is important
importance = pd.Series(
    model.feature_importances_,
    index=X.columns
)
importance.sort_values(ascending=False)

Creatinine_Levels       0.265193
LDL_Cholesterol         0.247178
Insulin_Levels          0.216601
OGTT                    0.135280
Uric_Acid_Levels        0.107804
Random_Blood_Glucose    0.027943
dtype: float64

In [ ]:
# task :- train this model for 10 columns and deploy it on streamlit
# post on linkedln